// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package virtualaccount

import (
	"database/sql"
)

type Accountinfo struct {
	AccountID string
	// not can be negtive
	Balance   string
	CreatedAt sql.NullTime
	Version   int32
}

type HisBuy struct {
	TaskID    string
	Symbol    string
	AccountID string
	BuyPrice  string
	Quantity  int32
	Trigger   string
	CreatedAt sql.NullTime
}

type HisSell struct {
	TaskID    string
	Symbol    string
	AccountID string
	SellPrice string
	Quantity  int32
	Income    string
	Trigger   string
	CreatedAt sql.NullTime
}

type HoldSymbol struct {
	AccountID string
	Symbol    string
	Quantity  int32
	CreatedAt sql.NullTime
}

type ProcessingTask struct {
	AccountID string
	TaskID    string
	Symbol    string
	CreatedAt sql.NullTime
}
