// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package symbol

import (
	"database/sql"
	"time"
)

type _2023 struct {
	Tradingtime time.Time
	Price       string
	Volume      int64
	Eventnum    int32
	Insrate     int32
	Nextrate    int32
	Formt       bool
	CreatedAt   sql.NullTime
}
